// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/journal/DarkGrid.tsx": () => import("../components/mockups/journal/DarkGrid.tsx"),
  "./components/mockups/journal/TimelineStream.tsx": () => import("../components/mockups/journal/TimelineStream.tsx"),
  "./components/mockups/journal/WarmEditorial.tsx": () => import("../components/mockups/journal/WarmEditorial.tsx")
};
